### ISSUE TITLE
Interpreter Missing Java Files

### ISSUE THREAD

**Issue by JeremyBolster** [barryWarnock/IDIOT-Interpreter#14]
All the Command Classes have not been uploaded and the interpreter does not work.

**Comment by barryWarnock** [comment]
they are all in Command.java, making 20 different 20 line files just makes more work.

**Comment by barryWarnock** [comment]
sorry I saved in the wrong directory.

**Comment by JeremyBolster** [comment]
It looks good now, thanks!
