### ISSUE TITLE
Helpful Hints Has No Hints :(

### ISSUE THREAD

**Issue by JeremyBolster** [barryWarnock/IDIOT-Interpreter#19]
Helpful hints requires some hints to make it helpful. 
PS. Not neccessary but It would be nice if the text wasn't in a pane that looks editable, maybe give it a border or use a different type of pane?

**Comment by ghost** [comment]
Sorry boys, gonna do some work to this tomorrow, you guys have been productive, and i've been a bag of shit lol

**Comment by JeremyBolster** [comment]
No worries.

**Comment by ghost** [comment]
done
