### ISSUE TITLE
Opening files does not create a close tab button

### ISSUE THREAD

**Issue by JeremyBolster** [barryWarnock/IDIOT-Interpreter#2]

**Comment by barryWarnock** [comment]
Is this still an issue or can we close it?

**Comment by TimHillier** [comment]
we can close it

**Comment by JeremyBolster** [comment]
If you want to close an issue, make sure the issue no longer exists.

**Comment by JeremyBolster** [comment]
This issue only effects non-.IDIOT files for some unknown reason.
