### ISSUE TITLE
Interpreter hangs with blank lines

### ISSUE THREAD

**Issue by JeremyBolster** [barryWarnock/IDIOT-Interpreter#9]
Putting a List of ten blank lines into the interpreter makes it fail.

**Comment by barryWarnock** [comment]
I managed to hang it up just by putting:
START
PRINT (hello)
END
into the interpreter and mashing on compileIcon, I think this might be something to do with compileAction.

**Comment by JeremyBolster** [comment]
I'll look at it

**Comment by barryWarnock** [comment]
I even managed to get
START
(23 blank lines)
PRINT (hey)
END
to work, I'm closing this and adding an unexplained Interpreter hang issue in its place
